version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
    restart: always
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nginxNetwork
networks:
  nginxNetwork: