#未完成
version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    networks:
      - kafkaNetwork
    expose:
      - "2181"

  kafka1:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9094:9094"
    expose:
      - "9093"
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://localhost:9094 #指定 Kafka 广播给客户端的监听地址
      #INSIDE://kafka:9093：用于内部通信，广播地址为容器内部的 kafka 主机名，端口 9093。
      #OUTSIDE://localhost:9094：用于外部通信.

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT #用于定义不同监听器的安全协议。
      #INSIDE 和 OUTSIDE 两种监听器都使用 PLAINTEXT（明文传输）协议。

      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE #指定 Kafka broker 之间通信使用的监听器名称。表示 Kafka broker 之间将通过 INSIDE 监听器进行通信。

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://0.0.0.0:9094 #用于指定 Kafka 监听的地址

    networks:
      - kafkaNetwork

  kafka2:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9095:9095"
    expose:
      - "9093"
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://0.0.0.0:9095 #用于指定 Kafka 监听的地址

    networks:
      - kafkaNetwork
networks:
  kafkaNetwork:
