#未完成
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk
    restart: always
    networks:
      - kafkaNetwork
    expose:
      - "2181"
    volumes:
      - /etc/localtime:/etc/localtime

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    restart: always
    ports:
      - "9092:9092"
    environment:
      - 'TZ=Asia/Shanghai'
      - 'KAFKA_BROKER_ID=0'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.30.77:9092' #指定 Kafka Broker 向外部客户端通告的地址
      - 'KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092'
    volumes:
      - ./kafka1/data:/kafka/kafka-logs
    networks:
      - kafkaNetwork
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    restart: always
    ports:
      - "9093:9093"
    environment:
      - 'TZ=Asia/Shanghai'
      - 'KAFKA_BROKER_ID=1'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.30.77:9093' #指定 Kafka Broker 向外部客户端通告的地址
      - 'KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093'
    networks:
      - kafkaNetwork
    volumes:
      - ./kafka2/data:/kafka/kafka-logs

  kafka-manager:
    container_name: kafka-manager
    image: dushixiang/kafka-map
    restart: always
    ports:
      - '9001:8080'
    networks:
      - kafkaNetwork
    environment:
      DEFAULT_USERNAME: root
      DEFAULT_PASSWORD: 1
    volumes:
      - ./kafka-map/data:/usr/local/kafka-map/data

networks:
  kafkaNetwork: